# Generated by Django 4.2.5 on 2023-09-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosimetry', '0002_alter_consingment_no_of_boxes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Address',
        ),
        migrations.AddField(
            model_name='customer',
            name='Address_Line1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='Address_Line2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='Contact_Person',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='India', max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
