# Generated by Django 4.2.5 on 2023-09-27 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dosimetry', '0003_remove_customer_address_customer_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consingment',
            name='Dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
